name: Production CI/CD
on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: checker
  SERVICE_NAME: api
  DOCKERFILE_PATH: ./env/prod/Dockerfile
  DOCKER_COMPOSE_PATH: ./prod/docker-compose.yml
  ENV_DIR: ./env
  ENV: prod
  SERVER_IP: 31.129.96.24
jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build
        run: |
          docker build \
          -f ${{ env.DOCKERFILE_PATH }} \
          -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }} .

      - name: Docker Push
        run: |
          docker push \
          ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-env
          path: ${{ env.ENV_DIR }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-env
          path: ${{ env.ENV_DIR }}

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PK }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Rsync deployment
        run: |
          rsync -avz \
            --delete \
            --exclude='.*' \
            -e "ssh -p 22 -o StrictHostKeyChecking=no" \
            ${{ env.ENV_DIR }}/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}
      - name: Replace docker app version
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PK }}
          port: 22
          script: |
            cd ${{secrets.DEPLOY_PATH}}
            
            export ENV=${{ env.ENV }}
            export SERVER_IP=${{ env.SERVER_IP }}
            
            export APP_VERSION=${{ needs.build.outputs.version }}
            
            
            docker pull supermetrolog/checker:${APP_VERSION}
            
            docker rm -f ${{ env.SERVICE_NAME }} || true
            
            docker-compose -f ${{ env.DOCKER_COMPOSE_PATH }} up -d ${{ env.SERVICE_NAME }}